name: build and push
on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
  workflow_dispatch: # on button click

jobs:
  build_n_push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: yimiaoxiehou/redis-sync:latest
